### PR TITLE
Add the HomeBrew Package Manager

### PR DESCRIPTION
**Pull request by ripytide**
Initially requested in https://github.com/steven-omaha/pacdef/issues/84

### CODE REVIEW

**Comment by InnocentZero** [comment]
LGTM, though I'm not certain about the brew cli args since I've never used brew.

**Review by InnocentZero — APPROVED** [review]

**Comment by ajeetdsouza** [comment]
Posted this on `pacdef` too, but why not use `brew`'s native `bundle` feature for this?

```bash
brew bundle --cleanup --no-upgrade --file=- <<EOF
brew "some-dependency-here"
EOF
```

**Comment by ripytide** [comment]
I saw that @ajeetdsouza but I encountered some issues with that approach.

At the moment the code is setup to work with backends which have a way to query, install and remove packages imperatively rather than declaratively which `brew bundle` does since we are implementing that declarativity ourselves.
A lot of the behaviour which we need to get from a backend such as `brew` is also not implemented as far as I can tell under the `bundle` subcommand such as listing missing dependencies which we need for `metapac unmanaged`.

Another issue I found was if we were to use `brew bundle cleanup` for something like `metapac clean` then we would need to create a brewfile which differentiates between casks and brews which resolved automatically when using `brew install [packages]`.

Is there any advantage to using the builtin `brew bundle` command rather than separate `brew list`, `brew install` and `brew remove` calls? If not then I don't see the value in reworking the code to accommodate it.

**Comment by niceEli** [comment]
very cool

**Pull request merged**
