### PR TITLE
add version subcommand

### LINKED ISSUE #46: Command to check which backends are found on the system.
Could be something like: `metapac backends`. And show extra information like which version was found and where the executable(s) for each backend was found.

### PR DESCRIPTION
**Pull request by InnocentZero**
Closes #46

### CODE REVIEW

**Comment by InnocentZero** [comment]
One problem with rustup is that it prints two lines to stderr and hence `run_command_for_stdout_ doesn't capture those lines, causing them to appear at first out  of order with everything else.

**Comment by ripytide** [comment]
I've re-worked some stuff to remove a dependency and added another dependency to remove a macro call.

**Review by ripytide — APPROVED** [review]
I approve now, but I'm biased since I've just added a commit so it might be best if you review it now too.

**Comment by InnocentZero** [comment]
This looks good. I forgot strum enum-iterator existed.

**Pull request merged**
